version: '3.8'
services:
  mongo:
    image: mongo:6.0.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017/tcp"
    volumes:
      - ./db_setup/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    image: art_exhibition_api:0.0.0
    env_file:
      - .compose-env
    depends_on:
      - mongo
    restart: always
    ports:
      - "4000:4000"

  client:
    image: art_exhibition_client:0.1.0
    env_file:
      - .env
    depends_on:
      - mongo
      - api
    restart: always
    ports:
      - "3000:3000"
